### ISSUE TITLE
[회의] 프로젝트 방향성 05월10일(금)

### ISSUE THREAD

**Issue by wjdalsths** [Parromu/front#8]
## 개요
회의
### 방향성
1. 노래 추천
2. 순위
3. +@ 역대 시상식

### 노래 추천: 
스포티파이 api 로 음악추천서비스
+ 유동적으로 움직이는 플리정보갖고와서 추천(바인딩)
+ 신곡추천

**Comment by HWANBINYOO** [comment]
음악 시상식 link
https://www.goldendisc.co.kr/ko/history 
https://www.seoulmusicawards.com/page/history?bookmark=past-winners
[https://namu.wiki/w/아시아%20아티스트%20어워즈](https://namu.wiki/w/%EC%95%84%EC%8B%9C%EC%95%84%20%EC%95%84%ED%8B%B0%EC%8A%A4%ED%8A%B8%20%EC%96%B4%EC%9B%8C%EC%A6%88)
[https://namu.wiki/w/지니%20뮤직%20어워드/역대%20시상식](https://namu.wiki/w/%EC%A7%80%EB%8B%88%20%EB%AE%A4%EC%A7%81%20%EC%96%B4%EC%9B%8C%EB%93%9C/%EC%97%AD%EB%8C%80%20%EC%8B%9C%EC%83%81%EC%8B%9D)
https://www.grammy.com/awards/66th-annual-grammy-awards-2023

**Comment by HWANBINYOO** [comment]
음악 차트 link 
https://github.com/KoreanThinker/billboard-json
https://github.com/max-jang/korea-music-chart-api
